spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/book_details
spring.datasource.username=postgres
spring.datasource.password=fsr1202

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
